//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace equipmentMangement
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class reservations_dbEntities1 : DbContext
    {
        public reservations_dbEntities1()
            : base("name=reservations_dbEntities1")
        {
            // eager loading enabled
            this.Configuration.LazyLoadingEnabled = true;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<equipment> equipment { get; set; }
        public virtual DbSet<reservations> reservations { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
